INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('agoth-charge-subject', 'citizenId', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('agoth-charge-victim', 'citizenId', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('cifs-missing-person', 'idCard', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('cifs-report-verification', 'thaiNin', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('coj-arrest-warrants', 'accCardId', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('dca-thailand-passport', 'thaiNin', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('dep-moi-dep-cripple', 'thaiNin', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('djop-juvenile-offender', 'citizenCardNumber', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('dlt-car-license-new', 'citizenCardNumber', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('dlt-driver-license-new', 'citizenCardNumber', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('doc-prisoner', 'citizenCardNumber', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('doc-prisoner-images', 'citizenCardNumber', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('doc-prisoner-no-just', 'citizenCardNumber', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('doc-reg-seize', 'citizenCardNumber', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('dol-moi-dol-land-and-condominium-titles', 'thaiNin', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('dopa-moi-dopa-addresses', 'thaiNin', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('dopa-moi-dopa-alien', 'thaiNin', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('dopa-moi-dopa-birth-certificates', 'thaiNin', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('dopa-moi-dopa-border-passes', 'thaiNin', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('dopa-moi-dopa-divorce-certificates', 'thaiNin', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('dopa-moi-dopa-marriage-certificates', 'thaiNin', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('dopa-moi-dopa-person', 'thaiNin', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('dopa-moi-dopa-person-changelastname', 'thaiNin', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('dopa-moi-dopa-person-changename-primary', 'thaiNin', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('dopa-moi-dopa-person-face-photo', 'thaiNin', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('dopa-moi-dopa-por4-licenses', 'thaiNin', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('dopa-moi-dopa-thai-id-cards', 'thaiNin', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('dop-probationee', 'citizenCardNumber', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('dsd-moi-dsd-workforce-developments', 'thaiNin', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('idb-directory-dimension-person', 'accusedCitizenId', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('idb-released-offender', 'citizenCardNumber', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('jfo-jfo-case', 'citizenId', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('led-bankruptcy-case', 'defendantId', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('moac-moi-moac-fisheries-illegal-fishing-cases', 'thaiNin', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('mof-moi-mof-register-of-taxpayers', 'thaiNin', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('nacc-moi-nacc-corruption-accuseds', 'thaiNin', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('nhso-moi-nhso-health-insurance-rights', 'thaiNin', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('rlpd-crime-defendant-compensation', 'dftCitizenId', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('rlpd-crime-victim-compensation', 'victimCitizenId', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('rlpd-requestors', 'personNationalIdentificationId', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('rtp-criminal', 'citizenCardNumber', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('rtp-missing-person-case', 'citizenCardNumber', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('sso-employee-employment', 'ssoNum', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('sso-employment', 'ssoNum', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('idb-person-report', 'thaiNin', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('idb-contact-report', 'thaiNin', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('idb-asset-report', 'thaiNin', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('idb-justice-event-report', 'thaiNin', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('idb-education-report', 'thaiNin', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('idb-dop-person-report', 'thaiNin', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('idb-djop-person-report', 'thaiNin', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('idb-doc-person-report', 'thaiNin', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('idb-dxc-person-report', 'thaiNin', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('idb-career-report', 'thaiNin', 'thaiNin',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('agoth-charge-subject', '{address} {moo} {soi} {road} {tambolName} {amphurName} {provinceName} {zipCode}', 'address',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('agoth-charge-victim', '{address} {moo} {soi} {road} {tambolName} {amphurName} {provinceName} {zipCode}', 'address',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('coj-arrest-warrants', '{accAddno} {accNear} {accVilno} {accSoi} {accRoad} {accSubDistrictText} {accDistrictText} {accProvinceText}', 'address',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('dbd-commercial-registrant', '{address}', 'address',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('dlt-car-license-new', '{addressOwner1} {addressOwner2}', 'address',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('doc-prisoner', '{addressNoText} {addressMooText} {addressRoadText} {addressSoiText} {addressMooBanText} {addressTumbonText} {addressAmphurText} {addressProvinceText} {addressPostCode}', 'address',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('doc-prisoner-no-just', '{addressNoText} {addressMooText} {addressRoadText} {addressSoiText} {addressMooBanText} {addressTumbonText} {addressAmphurText} {addressProvinceText} {addressPostCode}', 'address',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('dopa-citizen', '{homeAddress}', 'address',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('dopa-moi-dopa-addresses', '{houseNo} {villageNo} {roadDesc} {alleyWayDesc} {alleyDesc} {subdistrictDesc} {districtDesc} {provinceDesc}', 'address',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('dopa-moi-dopa-birth-certificates', '{houseRegistrationNo} {houseRegistrationAlleyWayDesc} {houseRegistrationAlleyDesc} {houseRegistrationRoadDesc} {houseRegistrationVillageNo} {houseRegistrationSubdistrictDesc} {houseRegistrationDistrictDesc} {houseRegistrationProvinceDesc}', 'address',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('dopa-moi-dopa-border-passes', '{houseNo} {houseAlleyWayDesc} {houseAlleyDesc} {houseVillageNo} {houseRoadDesc} {houseSubdistrictDesc} {houseDistrictDesc} {houseProvinceDesc}', 'address',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('dopa-moi-dopa-person-changelastname', '{hno} {trokDesc} {soiDesc} {thanonDesc} {districtDesc} {amphorDesc} {provinceDesc}', 'address',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('dopa-moi-dopa-por4-licenses', 'hno} {soi} {trok} {thanon} {districtDesc} {amphorDesc} {provinceDesc', 'address',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('dopa-moi-dopa-thai-id-cards', 'addressHouseNo} {addressAlleyWayDesc} {addressAlleyDesc} {addressVillageNo} {addressRoadDesc} {addressSubdistrictDesc} {addressDistrictDesc} {addressProvinceDesc', 'address',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('dop-probationee', 'homeNumber} {soi} {street} {moo} {village} {subDistrictName} {districtName} {provinceName', 'address',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('mof-moi-mof-register-of-taxpayers', '{ouseNumber} {houseIdNumber} {soiName} {yaek} {villageName} {floorNumber} {buildingName} {roomNumber} {streetName} {mooNumber} {thambolName} {amphurName} {provinceName} {postCode}', 'address',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('mof-registrant', 'addrNo} {addrVillage} {addrFloor} {addrMoo} {addrSoi} {addrSubSoi} {addrRoad} {addrSubDist} {addrDist} {addrProv} {addrPost', 'address',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('rlpd-requestors', '{personAddressFullText}', 'address',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('rtp-criminal', '{lastAddressProvince} {lastAddress}', 'address',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('agoth-charge-subject', 'telephone', 'phone',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('agoth-charge-victim', 'telephone', 'phone',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('coj-arrest-warrants', 'accTel', 'phone',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('dopa-moi-dopa-thai-id-cards', 'phoneNumber', 'phone',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('dsd-moi-dsd-workforce-developments', 'telNo', 'phone',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('mof-registrant', 'phoneMobile', 'phone',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('rlpd-requestors', 'telephoneNumber', 'phone',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('agoth-charge-subject', 'occupationName', 'career',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('agoth-charge-victim', 'occupationName', 'career',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('coj-arrest-warrants', 'accOccupation', 'career',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('dopa-moi-dopa-border-passes', 'occupation', 'career',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('mof-registrant', 'workCode', 'career',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('rlpd-crime-defendant-compensation', 'dftCareer', 'career',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('rlpd-crime-victim-compensation', 'victimCareer', 'career',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('rlpd-requestors', 'personOccupationText', 'career',NULL);
INSERT INTO public.data_set_response_global_field_map(data_set_id, local_field, global_field_id,format) VALUES ('rtp-criminal', 'occupation', 'career',NULL);
